### ISSUE TITLE
java.net.BindException: Address already in use error with some disabled tests

### ISSUE THREAD

**Issue by DPorcheron** [JensPiegsa/wiremock-extension#5]
Hello,

First of all, thanks for this nice WireMockExtension, it's really appreciated.
I just get an error on the 0.3.1 version. When you have some disabled tests in a test class, it seems that the WireMockExtension start a server in the postProcessTestInstance but never stop it. So the other next tests just fail cause there is already a running server on this port. Obviously I have this issue cause I need to run my WireMock server on the same port for each test. 
Let see this simple example to show the problem : 
```
@ExtendWith(WireMockExtension.class)
class SimpleTest {
    @InjectServer
    private WireMockServer server;

    @ConfigureWireMock
    private final Options options = wireMockConfig();

    @Test
    void should_not_fail_test() {
        assertThat(server.isRunning()).isTrue(); // (1) OK
    }

    @Test
    @Disabled
    void should_not_fail_disabled_test() {
        assertThat(server.isRunning()).isTrue(); // (2) OK, disabled
    }

    @Test
    @Disabled
    void should_not_fail_another_disabled_test() {
        assertThat(server.isRunning()).isTrue(); // (3) Failed with Address already in use
    }
}
```
Thanks in advance.

**Comment by clemstoquart** [comment]
Hi,

I can't reproduce with the `0.4.0` release.

**Comment by DPorcheron** [comment]
Hello,

As @clemstoquart said, it's not reproducible in 0.4.0 release.
Let's says that is fixed :)

Thanks
